name: Code Tests

on: 
    push:
    pull_request:
        branches: [master]


jobs:
    super-lint:
        name: Code Tests
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install dependencies
              run: dotnet restore

            - name: Build
              run: dotnet build --configuration Release --no-restore

            - name: Run Tests
              run: dotnet test --no-restore --verbosity normal
  
            - name: Run Super-Linter
              uses: github/super-linter@v4
              env:
                  DEFAULT_BRANCH: master
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  JSCPD_CONFIG_FILE: ".jscpd.json"
                  FILTER_REGEX_EXCLUDE: ConsoleMenu.Tests/.*