name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  #build:
  #  runs-on: windows-latest

  #  steps:
  #    - name: Checkout
  #      uses: actions/checkout@v2
  #    - name: Setup .NET
  #      uses: actions/setup-dotnet@v1
  #      with:
  #        dotnet-version: 6.0.x
  #    - name: Restore dependencies
  #      run: dotnet restore

  Format_check:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: |
          dotnet restore -v:normal --ignore-failed-sources
      - name: Format
        #run: dotnet format -v:diag --verify-no-changes
        run: dotnet format --no-restore -v:normal --verify-no-changes

  Desktop:
    needs: Format_check
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build Desktop
        run: dotnet build Desktop/Desktop.csproj  --no-restore
      - name: Tests
        run: dotnet test Desktop/Desktop.csproj --no-build --verbosity normal